site_name: wraps
site_author: nekitdev
site_description: Meaningful and safe wrapping types.

repo_name: nekitdev/wraps
repo_url: https://github.com/nekitdev/wraps

remote_branch: github-pages

nav:
  - Index: "index.md"
  - Usage: "usage.md"
  - Reference:
    - Option: "reference/option.md"
    - Result: "reference/result.md"
    - Either: "reference/either.md"
    - Early: "reference/early.md"
    - Future: "reference/future.md"
    - Future Option: "reference/future_option.md"
    - Future Result: "reference/future_result.md"
    - Future Either: "reference/future_either.md"
    - Errors: "reference/errors.md"
    - Typing: "reference/typing.md"
  - Changelog: "changelog.md"
  - Security: "security.md"
  - Code of Conduct: "code_of_conduct.md"
  - Contributing: "contributing.md"

watch:
  - docs
  - wraps

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate

      primary: deep purple
      accent: light blue

      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default

      primary: deep orange
      accent: light blue

      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

plugins:
  - search

  - mkdocstrings:
      handlers:
        python:
          options:
            members_order: source
            show_signature_annotations: true

          paths: [wraps]

          import:
            - https://docs.python.org/3/objects.inv

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
