site_name: wraps
site_author: nekitdev
site_description: Meaningful and safe wrapping types.

repo_name: nekitdev/wraps
repo_url: https://github.com/nekitdev/wraps

remote_branch: github-pages

nav:
  - Index: "index.md"
  - Reference:
    - Option: "reference/option.md"
    - Result: "reference/result.md"
    - Early: "reference/early.md"
    - Either: "reference/either.md"
    - ReAwaitable: "reference/reawaitable.md"
    - Future:
      - Base: "reference/future/base.md"
      - Option: "reference/future/option.md"
      - Result: "reference/future/result.md"
      - Either: "reference/future/either.md"
      - Typing: "reference/future/typing.md"
    - Wraps: "reference/wraps.md"
    - Markers: "reference/markers.md"
    - Panics: "reference/panics.md"
  - Changelog: "changelog.md"
  - Security: "security.md"
  - Code of Conduct: "code_of_conduct.md"
  - Contributing: "contributing.md"

watch:
  - docs
  - wraps

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate

      primary: deep purple
      accent: light blue

      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default

      primary: light blue
      accent: deep purple

      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

plugins:
  - search

  - mkdocstrings:
      handlers:
        python:
          options:
            members_order: source
            show_signature_annotations: true

          paths: [wraps]

          import:
            - https://docs.python.org/3/objects.inv
            - http://nekitdev.github.io/typing-aliases/objects.inv

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
