site_name: wraps
site_author: nekitdev
site_description: Meaningful and safe wrapping types.

repo_name: nekitdev/wraps
repo_url: https://github.com/nekitdev/wraps

remote_branch: github-pages

nav:
  - Index: "index.md"
  - Reference:
    - Primitives:
      - Option: "reference/primitives/option.md"
      - Result: "reference/primitives/result.md"
      - Either: "reference/primitives/either.md"
      - ReAwaitable: "reference/primitives/reawaitable.md"
      - Typing: "reference/primitives/typing.md"
    - Early:
      - Decorators: "reference/early/decorators.md"
      - Errors: "reference/early/errors.md"
    - Futures:
      - Base: "reference/futures/base.md"
      - Option: "reference/futures/option.md"
      - Result: "reference/futures/result.md"
      - Either: "reference/futures/either.md"
      - Typing:
        - Base: "reference/futures/typing/base.md"
        - Derived: "reference/futures/typing/derived.md"
    - Wraps:
      - Option: "reference/wraps/option.md"
      - Result: "reference/wraps/result.md"
      - Futures: "reference/wraps/futures.md"
      - ReAwaitable: "reference/wraps/reawaitable.md"
      - Error Types: "reference/wraps/error_types.md"
    - Markers: "reference/markers.md"
    - Panics: "reference/panics.md"
  - Changelog: "changelog.md"
  - Security: "security.md"
  - Code of Conduct: "code_of_conduct.md"
  - Contributing: "contributing.md"

watch:
  - docs
  - wraps

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate

      primary: deep purple
      accent: light blue

      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default

      primary: light blue
      accent: deep purple

      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

plugins:
  - search

  - mkdocstrings:
      handlers:
        python:
          options:
            members_order: source
            show_signature_annotations: true

          import:
            - https://docs.python.org/3/objects.inv
            - http://nekitdev.github.io/typing-aliases/objects.inv

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
