site_name: wraps
site_author: nekitdev
site_description: Meaningful and safe wrapping types.

repo_name: nekitdev/wraps
repo_url: https://github.com/nekitdev/wraps

remote_branch: github-pages

nav:
  - Index: "index.md"
  - Reference:
      - Option: "reference/option.md"
      - Result: "reference/result.md"
      - Either: "reference/either.md"
      - Early:
          - Decorators: "reference/early/decorators.md"
          - Errors: "reference/early/errors.md"
      - Futures:
          - ReAwaitable: "reference/futures/reawaitable.md"
          - Future: "reference/futures/future.md"
          - Option: "reference/futures/option.md"
          - Result: "reference/futures/result.md"
          - Either: "reference/futures/either.md"
          - Typing: "reference/futures/typing.md"
      - Parse:
          - Simple: "reference/parse/simple.md"
          - Normal: "reference/parse/normal.md"
          - Format: "reference/parse/format.md"
      - Markers: "reference/markers.md"
      - Panics: "reference/panics.md"
      - Errors: "reference/errors.md"
      - Typing: "reference/typing.md"
  - Changelog: "changelog.md"
  - Security: "security.md"
  - Code of Conduct: "code_of_conduct.md"
  - Contributing: "contributing.md"

watch:
  - docs
  - src

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate

      primary: deep purple
      accent: light blue

      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default

      primary: light blue
      accent: deep purple

      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

plugins:
  - search

  - mkdocstrings:
      handlers:
        python:
          options:
            members_order: source
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_signature_annotations: true

          import:
            - https://docs.python.org/3/objects.inv
            - http://nekitdev.github.io/typing-aliases/objects.inv

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
