name: docs

on:
  push:
    branches:
      - main

env:
  bot-name: nekit[bot]
  bot-email: bot@nekit.dev
  python-version: "3.12"

jobs:
  docs:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python ${{ env.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.python-version }}

      - name: Setup uv
        uses: yezz123/setup-uv@v4

      - name: Setup bot user
        run: |
          git config --local user.name ${{ env.bot-name }}
          git config --local user.email ${{ env.bot-email }}

      - name: Deploy the documentation
        run: uv run mkdocs gh-deploy --force
